spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/data/h2/mummoomH2;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:

    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        # generate-ddl : false로 바꾸기
        generate-ddl : true
        hibernate:
            # ddl-auto: none으로 바꾸기
            ddl-auto: none
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

        properties:
            hibernate:
            show_sql: true
            format_sql: true
            dialect: org.hibernate.dialect.MySQL5Dialect
    h2:
        console:
            enabled: true
    profiles:
        include: real-db

# 여기서부터 로그인 부분
    servlet:
        encoding:
            charset: UTF-8 #utf-8 encoding
            force : true
    main:
        allow-bean-definition-overriding: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 658312263287-danrtjun8da6im0r5rudcsg6e6au5kok.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile, email

                    kakao:
                        client-id: 805bbf422b921a63ed8df325ed13428b
                        client-secret: KMbqaAreZ6U2sZkOr5Q0qOPGrUyRQyHG
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        scope: profile_nickname, profile_image, account_email
                        client-name: kakao
                        client-authentication-method: POST

                provider:
                    kakao:
                        authorization_uri: https://kauth.kakao.com/oauth/authorize
                        token_uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user_name_attribute: id

# 여기까지 로그인 끝

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

client:
    origins: http://localhost:8080


# http://localhost:8080/swagger-ui.html

